cluster: "
  sbatch
  --parsable
  -A mrc-bsu-sl2-cpu
  -p icelake
  -t {resources.time_min}
  --mem={resources.mem_mb}
  -c {resources.cpus}
  -o logs/{rule}_{wildcards}.out
  -e logs/{rule}_{wildcards}.err
"
jobs: 100
rerun-incomplete: true
max-jobs-per-second: 1
printshellcmds: true
default-resources: [cpus=1, mem_mb=3000, time_min=30]
nolock: true
keep-going: true
cluster-status: ./profiles/default/cluster-status.py
cluster-cancel: scancel
max-status-checks-per-second: 1
latency-wait: 20
