# awk -F '\t' '{ if ($9 == "ge" || $9 == "aptamer") { print " - "$2 } }' data/eqtl-catalogue/eqtl-catalogue-metadata.tsv 
eqtl_catalogue_dataset_ids:
 - QTD000001
 - QTD000006
 - QTD000011
 - QTD000016
 - QTD000021
 - QTD000026
 - QTD000031
 - QTD000036
 - QTD000041
 - QTD000046
 - QTD000051
 - QTD000056
 - QTD000061
 - QTD000075
 - QTD000085
 - QTD000090
 - QTD000095
 - QTD000100
 - QTD000105
 - QTD000110
 - QTD000116
 - QTD000121
 - QTD000126
 - QTD000131
 - QTD000136
 - QTD000141
 - QTD000146
 - QTD000151
 - QTD000156
 - QTD000161
 - QTD000166
 - QTD000171
 - QTD000176
 - QTD000181
 - QTD000186
 - QTD000191
 - QTD000196
 - QTD000201
 - QTD000206
 - QTD000211
 - QTD000216
 - QTD000221
 - QTD000226
 - QTD000231
 - QTD000236
 - QTD000241
 - QTD000246
 - QTD000251
 - QTD000256
 - QTD000261
 - QTD000266
 - QTD000271
 - QTD000276
 - QTD000281
 - QTD000286
 - QTD000291
 - QTD000296
 - QTD000301
 - QTD000306
 - QTD000311
 - QTD000316
 - QTD000321
 - QTD000326
 - QTD000331
 - QTD000336
 - QTD000341
 - QTD000346
 - QTD000351
 - QTD000356
 - QTD000361
 - QTD000366
 - QTD000373
 - QTD000379
 - QTD000384
 - QTD000389
 - QTD000394
 - QTD000399
 - QTD000404
 - QTD000409
 - QTD000414
 - QTD000419
 - QTD000424
 - QTD000429
 - QTD000434
 - QTD000439
 - QTD000444
 - QTD000449
 - QTD000454
 - QTD000459
 - QTD000464
 - QTD000469
 - QTD000474
 - QTD000479
 - QTD000484
 - QTD000489
 - QTD000494
 - QTD000499
 - QTD000504
 - QTD000509
 - QTD000514
 - QTD000519
 - QTD000524
 - QTD000529
 - QTD000534
 - QTD000539
 - QTD000544
 - QTD000549
 - QTD000554
 - QTD000559
 - QTD000584
pqtl_eqtl_coloc_dataset_ids:
 - QTD000373 # Lepik 2017 (blood)
 - QTD000341 # GTEx thyroid 
 - QTD000116 # GTEx adipose (subcutaneous)
 - QTD000021 # BLUEPRINT Monocyte
 - QTD000539 # TwinsUK LCL
 - QTD000266 # GTEx liver
finngen_gwas_ids:
 - AUTOIMMUNE
 - I9_HYPTENS
 - T2D_WIDE
 - K11_IBD_STRICT
 - T1D
 - RHEUMA_SEROPOS_WIDE
 - HEIGHT_IRN
 - WEIGHT_IRN
 - RX_STATIN
 - C3_BREAST_EXALLC
ukbb_saige_icd_codes:
 - "250.2" # Type 2 diabetes
 - "401" # Hypertension
 - "244" # Hypothyroidism
gwas_eqtl_coloc_ids:
 - "AUTOIMMUNE-QTD000373" # Lepik blood
 - "AUTOIMMUNE-QTD000341" # GTEx thyroid
 - "AUTOIMMUNE-QTD000095" # GENCORD LCL
 - "AUTOIMMUNE-QTD000021" # BlUEPRINT monocytes
 - "AUTOIMMUNE-QTD000031" # BLUEPRINT T cells
 - "T2D_WIDE-QTD000373" # Lepik blood
 - "T2D_WIDE-QTD000090" # FUSION adipose
 - "T2D_WIDE-QTD000266" # GTEx liver
 - "T2D_WIDE-QTD000321" # GTEx small intestine
 - "T2D_WIDE-QTD000296" # GTEx pancreas
 - "I9_HYPTENS-QTD000373" # Lepik blood
 - "I9_HYPTENS-QTD000549" # TwinsUK blood
 - "I9_HYPTENS-QTD000256" # GTEx left heart ventricle
 - "I9_HYPTENS-QTD000136" # GTEx artery coronary
 - "I9_HYPTENS-QTD000261" # GTEx kidney
 - "K11_IBD_STRICT-QTD000373" # Lepik blood
 - "K11_IBD_STRICT-QTD000001" # Alasoo Naive macrophage
 - "K11_IBD_STRICT-QTD000031" # BLUEPRINT T cells
 - "K11_IBD_STRICT-QTD000321" # GTEx small intestine
 - "K11_IBD_STRICT-QTD000261" # GENCORD LCL
 - "T1D-QTD000373" # Lepik blood
 - "T1D-QTD000296" # GTEx pancreas
 - "T1D-QTD000031" # BLUEPRINT T cells
 - "T1D-QTD000095" # GENCORD LCL
 - "T1D-QTD000554" # Pancreatic islet
 - "RHEUMA_SEROPOS_WIDE-QTD000373" # Lepik blood
 - "RHEUMA_SEROPOS_WIDE-QTD000549" # TwinsUK blood
 - "RHEUMA_SEROPOS_WIDE-QTD000519" # Steinberg Synovium naive
 - "RHEUMA_SEROPOS_WIDE-QTD000031" # BLUEPRINT T cells
 - "RHEUMA_SEROPOS_WIDE-QTD000095" # GENCORD LCL
 - "HEIGHT_IRN-QTD000373" # Lepik blood
 - "HEIGHT_IRN-QTD000549" # TwinsUK blood
 - "HEIGHT_IRN-QTD000271" # GTEx lung
 - "HEIGHT_IRN-QTD000301" # GTEx pituitary
 - "HEIGHT_IRN-QTD000549" # TwinsUK blood
 - "WEIGHT_IRN-QTD000373" # Lepik blood
 - "WEIGHT_IRN-QTD000090" # FUSION adipose
 - "WEIGHT_IRN-QTD000296" # GTEx pancreas
 - "WEIGHT_IRN-QTD000321" # GTEx small intestine
 - "WEIGHT_IRN-QTD000301" # GTEx pituitary
 - "RX_STATIN-QTD000373" # Lepik blood
 - "RX_STATIN-QTD000549" # TwinsUK blood
 - "RX_STATIN-QTD000256" # GTEx left heart ventricle
 - "RX_STATIN-QTD000136" # GTEx artery coronary
 - "RX_STATIN-QTD000261" # GTEx kidney
 - "C3_BREAST_EXALLC-QTD000373" # Lepik blood 
 - "C3_BREAST_EXALLC-QTD000211" # GTEx breast
 - "C3_BREAST_EXALLC-QTD000121" # GTEx adipose visceral
 - "C3_BREAST_EXALLC-QTD000031" # BLUEPRINT T cells
 - "C3_BREAST_EXALLC-QTD000116" # GTEX adipose subcutaneous 
simulation_genes:
  - "PTPN22"
  - "IL21"
  - "IFT172"
