gtex_tissues:
 - Adipose_Subcutaneous
 - Adipose_Visceral_Omentum
 - Adrenal_Gland
 - Artery_Aorta
 - Artery_Coronary
 - Artery_Tibial
 - Brain_Amygdala
 - Brain_Anterior_cingulate_cortex_BA24
 - Brain_Caudate_basal_ganglia
 - Brain_Cerebellar_Hemisphere
 - Brain_Cerebellum
 - Brain_Cortex
 - Brain_Frontal_Cortex_BA9
 - Brain_Hippocampus
 - Brain_Hypothalamus
 - Brain_Nucleus_accumbens_basal_ganglia
 - Brain_Putamen_basal_ganglia
 - Brain_Spinal_cord_cervical_c-1
 - Brain_Substantia_nigra
 - Breast_Mammary_Tissue
 - Cells_Cultured_fibroblasts
 - Cells_EBV-transformed_lymphocytes
 - Colon_Sigmoid
 - Colon_Transverse
 - Esophagus_Gastroesophageal_Junction
 - Esophagus_Mucosa
 - Esophagus_Muscularis
 - Heart_Atrial_Appendage
 - Heart_Left_Ventricle
 - Kidney_Cortex
 - Liver
 - Lung
 - Minor_Salivary_Gland
 - Muscle_Skeletal
 - Nerve_Tibial
 - Ovary
 - Pancreas
 - Pituitary
 - Prostate
 - Skin_Not_Sun_Exposed_Suprapubic
 - Skin_Sun_Exposed_Lower_leg
 - Small_Intestine_Terminal_Ileum
 - Spleen
 - Stomach
 - Testis
 - Thyroid
 - Uterus
 - Vagina
# FIXME: Can these be dynamically calculated at runtime?
# awk '{ if ($9 == "ge" || $9 == "aptamer") { print $2 } }' data/eqtl-catalogue/eqtl-catalogue-metadata.tsv 
eqtl_catalogue_dataset_ids:
 - QTD000001
 - QTD000006
 - QTD000011
 - QTD000016
 - QTD000021
 - QTD000026
 - QTD000056
 - QTD000061
 - QTD000085
 - QTD000090
 - QTD000095
 - QTD000100
 - QTD000110
 - QTD000116
 - QTD000211
 - QTD000216
 - QTD000221
 - QTD000266
 - QTD000271
 - QTD000281
 - QTD000291
 - QTD000296
 - QTD000301
 - QTD000306
 - QTD000316
 - QTD000326
 - QTD000331
 - QTD000336
 - QTD000341
 - QTD000346
 - QTD000351
 - QTD000356
 - QTD000361
 - QTD000366
 - QTD000373
 - QTD000379
 - QTD000384
 - QTD000389
 - QTD000394
 - QTD000399
 - QTD000404
 - QTD000409
 - QTD000414
 - QTD000419
 - QTD000424
 - QTD000429
 - QTD000504
 - QTD000519
 - QTD000524
 - QTD000529
 - QTD000534
 - QTD000539
 - QTD000544
 - QTD000549
 - QTD000559
 - QTD000584
pqtl_eqtl_coloc_dataset_ids:
 - QTD000373 # Lepik 2017 (blood)
 - QTD000341 # GTEx thyroid 
 - QTD000116 # GTEx adipose (subcutaneous)
 - QTD000021 # BLUEPRINT Monocyte
 - QTD000539 # TwinsUK LCL
finngen_gwas_ids:
 - AUTOIMMUNE
 - I9_HYPTENS
 - T2D_WIDE
gwas_eqtl_coloc_ids:
 - "AUTOIMMUNE-QTD000373" # Lepik blood
 - "AUTOIMMUNE-QTD000341" # GTEx thyroid
 - "AUTOIMMUNE-QTD000095" # GENCORD LCL
 - "AUTOIMMUNE-QTD000021" # BlUEPRINT monocytes
 - "AUTOIMMUNE-QTD000031" # BLUEPRINT T cells
 - "T2D_WIDE-QTD000373" # Lepik blood
 - "T2D_WIDE-QTD000090" # FUSION adipose
 - "T2D_WIDE-QTD000266" # GTEx liver
 - "T2D_WIDE-QTD000321" # GTEx small intestine
 - "T2D_WIDE-QTD000296" # GTEx pancreas
 - "I9_HYPTENS-QTD000373" # Lepik blood
 - "I9_HYPTENS-QTD000549" # TwinsUK blood
 - "I9_HYPTENS-QTD000256" # GTEx left heart ventricle
 - "I9_HYPTENS-QTD000136" # GTEx artery coronary
 - "I9_HYPTENS-QTD000261" # GTEx kidney
simulation_loci:
  - "PTPN22"
  - "IL21"
  - "IFT172"
