name: pipeline
channels:
  - conda-forge
  - bioconda 
dependencies:
  - snakemake==7.32.0
  - samtools
  - vcftools
  - tqdm
  - pyarrow>=3.0
  - python>=3.8
  - scikit-learn
  - bitarray
  - networkx
  - scipy
  - numpy>=1.20
  - pandas
  - pandas-plink
  - pip
  - packaging
  - pip:
    - bgen==1.2.10
