project:
  type: website

website:
  title: "coloc estimated eQTL priors"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eqtlgen-prior-estimation.qmd
        text: eQTLGen analysis

format:
  html:
    theme: cosmo
    toc: true
