---
title: "Density estimation"
format: html
editor: source
---

```{r}
library(ggplot2)
library(readr)
library(janitor)
library(dplyr)
library(patchwork)
library(tidyr)
library(biomaRt)
```

```{r}
hg38_mart <- useEnsembl(biomart = "ensembl", dataset = "hsapiens_gene_ensembl")

tss_data <- getBM(
  attributes = c("ensembl_gene_id", "transcription_start_site", "strand"),
  filters = "ensembl_gene_id",
  values = "",
  mart = hg38_mart
) |>
  as_tibble() |>
  rename(tss = transcription_start_site)

tss_data |> 
  summarise(n_tss = n(), .by = ensembl_gene_id) |> 
  count(n_tss)

tss_data |> 
  summarise(tss_range = diff(range(tss)), .by = ensembl_gene_id) |> 
  mutate(one_tss = tss_range == 0) |> 
  count(one_tss) |> 
  mutate(prop = n / sum(n))

tss_data |> 
  summarise(tss_range = diff(range(tss)), .by = ensembl_gene_id) |> 
  filter(tss_range > 0) |> 
  ggplot(aes(tss_range)) + 
  geom_histogram(binwidth = 10e3) + 
  coord_cartesian(xlim = c(0, 1e6)) + 
  theme_bw()

tss_data |> 
  summarise(tss_range = diff(range(tss)), .by = ensembl_gene_id) |> 
  pull(tss_range) |> 
  quantile()

tss_data |> 
  summarise(tss_range = diff(range(tss)), .by = ensembl_gene_id) |> 
  filter(tss_range > 0) |> 
  pull(tss_range) |> 
  quantile(seq(0, 1, by = 0.1))

tss_data |> 
  summarise(tss_range = diff(range(tss)), .by = ensembl_gene_id) |> 
  filter(tss_range > 0) |> 
  ggplot(aes(log(tss_range))) + 
  geom_histogram(binwidth = 0.25) + 
  theme_bw()
```

```{r}
raw_eqtlgen_data <- read_tsv(here::here("data/eqtlgen.txt"),
                             col_select = c(gene_symbol, snp_pos, gene_pos, pvalue),
                             name_repair = make_clean_names,
                             show_col_types = FALSE, progress = FALSE)

eqtlgen_data <- raw_eqtlgen_data |>
  filter(pvalue < 5 * 10^-8) |>
  group_by(gene_symbol) |>
  arrange(pvalue) |>
  filter(row_number() == 1) |>
  mutate(tss_distance = snp_pos - gene_pos) |> 
  ungroup()

eqtlgen_data

tss_values <- eqtlgen_data |> 
  filter(abs(tss_distance) <= 3e5) |> 
  # mutate(log_tss_distance = if_else(tss_distance <= 0, -log(-tss_distance), 
  #                                   log(tss_distance))) |> 
  pull(tss_distance)

dens <- density(tss_values, bw = "SJ", cut = 0, adjust = 5)
x <- dens$x
y <- dens$y
# x <- ifelse(x <= 0, -exp(-x), exp(x))
# y <- exp(y)

plot(x, y)

#flatten_dist <- 5e4
#flatten_ind <- abs(x) < flatten_dist
#flatten_value <- max(y[!flatten_ind])
#y[flatten_ind] <- flatten_value
#y <- y / sum(y)

plot(x, y)
plot(x, log(y))

dens_data <- tibble(x, y)

dens_data |> 
  ggplot(aes(x, y)) + 
  geom_point()

saveRDS(dens_data, "/home/jp2045/coloc-estimated-eqtl-priors/output/data/density.rds")
```

```{r}
plot_priors("Steinberg_2020_ge_synovium_naive.ENSG00000169629", 
            "TwinsUK_ge_skin.ENSG00000169629", 
            "chr2_block62", 
            tss2 = 112433519)
```

