---
title: "Finemapping analysis"
format: html
editor: source
---

```{r warning = FALSE, message = FALSE}
renv::load(here::here())

library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(forcats)
library(yaml)
library(glue)

devtools::load_all("~/coloc")
```

```{r}
compute_credible_set <- function(pips, alpha = 0.95) {
  pips_order <- order(pips, decreasing = TRUE)
  cum_pips <- cumsum(pips[pips_order])
  cs_size <- which.max(cum_pips >= alpha) 
  pips_order[1:cs_size]
}
```

```{r load-data}
config <- read_yaml(here::here("config.yaml"))
gwas_ids_eqtl_ids <- config$gwas_eqtl_coloc_ids
gwas_eqtl_finemapping <- expand_grid(
  chr = 1:22,
  gwas_id_eqtl_id = gwas_ids_eqtl_ids
  ) |>
  separate_wider_delim(gwas_id_eqtl_id, "-", names = c("gwas_id", "eqtl_id")) |>
  rowwise() |>
  mutate(file = here::here(
    glue("output/data/gwas-eqtl-finemapping-{gwas_id}-{eqtl_id}-{chr}.rds")
  )) |>
  mutate(data = list(read_rds(file))) |>
  unnest(data)

```

```{r}
cs_n_data <- gwas_eqtl_finemapping |>
  select(gene_name, gwas_id, eqtl_id, 
         ends_with("eqtl"), ends_with("gwas")) |>
  pivot_longer(
    -c(gene_name, gwas_id, eqtl_id), 
    values_to = "pip",
    names_to = "prior"
  ) |>
  summarise(cs = list(compute_credible_set(pip)), 
            .by = c(gene_name, prior, gwas_id, eqtl_id)) |>
  rowwise() |>
  mutate(cs_n = length(cs)) |>
  ungroup()
```

```{r}
cs_n_data |>
  mutate(prior = fct_reorder(factor(prior), cs_n)) |>
  ggplot(aes(prior, log(cs_n))) + 
  geom_boxplot() + 
  coord_flip() +
  facet_wrap(~gwas_id) + 
  theme_bw()
```

```{r}
cs_n_data |>
  mutate(single_cs = cs_n == 1) |>
  summarise(prop_single_cs = sum(single_cs) / n(),
           .by = c(prior, gwas_id)) |>
  mutate(prior = fct_reorder(factor(prior), prop_single_cs)) |>
  ggplot(aes(prior, prop_single_cs)) + 
  geom_point() + 
  coord_flip() + 
  facet_wrap(~gwas_id) + 
  theme_bw()
```

```{r}
cs_n_data |>
  filter(cs_n <= 20) |>
  count(cs_n, prior) |>
  ggplot(aes(cs_n, n)) + 
  geom_col() + 
  labs(
    y = "Count",
    x = "Size of single-causal variant CS"
  ) + 
  facet_wrap(~prior) + 
  theme_bw()
```